i1=int(input("enter the value for check the datatype-:"))
f1=float(input("enter the value for check the datatype-:"))
s1=str(input("enter the value for check the datatype-:"))
b1=bool(input("enter the value for check the datatype-:"))
c1=complex(input("enter the value for check the datatype-:"))
print(type(i1))
print(type(f1))
print(type(s1))
print(type(b1))